services:
  database:
    image: postgres:14
    container_name: coffee_db
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super-secure-password
      POSTGRES_DB: coffee_database
    volumes:
      - ./db:/var/lib/postgresql/data
